# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchzip,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig_0_16,
  zstd,
  name ? "zig-packages",
}:
let
  unpackZigArtifact =
    {
      name,
      artifact,
    }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig_0_16 ];
      }
      ''
        # workaround https://codeberg.org/ziglang/zig/issues/31866
        # https://github.com/Cloudef/zig2nix/issues/54
        mkdir "$TMPDIR/src" "$TMPDIR/cache" "$TMPDIR/cache/tmp"
        touch "$TMPDIR/src/build.zig"
        hash="$(cd "$TMPDIR/src" && zig fetch --global-cache-dir "$TMPDIR/cache" ${artifact})"
        mkdir "$out"
        tar zxvf "$TMPDIR/cache/p/$hash.tar.gz" --directory "$out/" --strip-components=1
      '';

  fetchZig =
    {
      name,
      url,
      hash,
      unpack,
    }:
    let
      artifact =
        if unpack then
          fetchzip {
            inherit url hash;
            nativeBuildInputs = [ zstd ];
          }
        else
          fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "#" url;
      url_base = builtins.elemAt parts 0;
      url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
      rev_base = builtins.elemAt parts 1;
      rev =
        if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null then rev_base else "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
      unpack,
    }:
    let
      parts = lib.splitString "://" url;
      proto = builtins.elemAt parts 0;
      path = builtins.elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash unpack;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash unpack;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
  # The packages, as real directories holding symlinked files, rather than as
  # a farm of symlinked directories.
  #
  # Zig runs a dependency's own build steps with the working directory set to
  # that dependency, and points at the program to run with a path counted in
  # directories up from there. Through a symlink the two disagree: Zig counts
  # from `<farm>/<package>/`, four directories below the root, while the kernel
  # resolves the working directory to `/nix/store/<hash>`, which is three, so
  # the path lands one short of where the program is.
  #
  # It works anyway when the build directory is `/build`, because the sum then
  # overshoots into the root and going above the root stays there. It fails
  # when the build directory is under `/nix/var/nix/builds`, which is where Nix
  # puts it when the sandbox is off. Real directories make the two depths
  # agree, so it works either way.
  #
  # The files have to be real as well, which is the expensive part and cannot
  # be avoided. `--symbolic-link` would leave them pointing into each
  # dependency's own store path, so that the farm is a few megabytes rather
  # than a second copy of every dependency -- but Zig's
  # `installHeadersDirectory` walks the directory and copies only the entries
  # whose kind is `.file`. Symlinked headers are skipped without a word, and
  # the first thing to include one fails with `'dcimgui.h' not found`.
  #
  # `--link` is not the way out. A hard link into a Nix output is a file the
  # builder did not create: inside the Linux sandbox the store is a separate
  # mount and `link` fails with `Invalid cross-device link`, while on Darwin it
  # succeeds and leaves root-owned files in the output, which Nix refuses while
  # canonicalising with `invalid ownership on file`.
  #
  # So it is a real copy, with `--reflink=auto` to share the blocks on a
  # filesystem that can. `nix store optimise` recovers the duplication after
  # the fact, hard-linking identical files across the store, which is the
  # store's own business to do and not a build's.
  copyFarm =
    farm: entries: pathDependencyPackages:
    runCommandLocal farm
      {
        # The packages whose own manifest declares a dependency by `.path`.
        # Zig 0.16.0 cannot build these through `zig build --system`: it spins
        # in userspace forever, because a `.path` dependency's hash is computed
        # against the system package directory during the fetch and against the
        # real global cache afterwards, and in that mode the two disagree. A
        # package that wants `--system` copies each of these into its build
        # root and passes `--fork=`; see the README.
        passthru = { inherit pathDependencyPackages; };
      }
      ''
        mkdir -p "$out"
        cp --recursive --reflink=auto --dereference --no-preserve=mode \
          ${linkFarm farm entries}/. "$out/"
      '';
in
copyFarm name
  [
    {
      name = "N-V-__8AAI8Hdw49zvJpQMT6mP3lUI2BU88KafEc3BkYlcu6";
      path = fetchZigArtifact {
        name = "boringssl";
        url = "git+https://github.com/google/boringssl#dd73e69a4e86fa178a4d19033c691e9b42cc1088";
        hash = "sha256-cSwDjwSPP13GB4as9Nwm8iQTN/K2ZP5T9wVHWTzYQA4=";
        unpack = true;
      };
    }
    {
      name = "N-V-__8AAEaRCwCsYb_rSsH72Pb6DNFQLSjdRzTFOVsJWcoB";
      path = fetchZigArtifact {
        name = "libdeflate";
        url = "git+https://github.com/ebiggers/libdeflate#92e6a0db9fa848d742f9eb286c92afc60f2c3dda";
        hash = "sha256-QVF2XL8Qu3mTszKKtx+8BExkTGkpMANXjkAe3XXPUJQ=";
        unpack = true;
      };
    }
    {
      name = "libxev-0.0.0-86vtcwIRFADbH4hk-EjROXxlrKIRPQdA41XiTSytYO-F";
      path = fetchZigArtifact {
        name = "libxev";
        url = "git+https://github.com/mitchellh/libxev#9ce8e8e6ff89e583258a7f8e7adeeeaeae8611bf";
        hash = "sha256-fOU1oxIxfoEgoLuWz7fVX6M+zmqpo7gqZObWiH/aDE0=";
        unpack = true;
      };
    }
    {
      name = "N-V-__8AABFJVQBMmGjr7hbydaG9qS3FWrGChwmOj7c-A6Xy";
      path = fetchZigArtifact {
        name = "lshpack";
        url = "git+https://github.com/litespeedtech/ls-hpack#38ceca78054d4175ba3f6411b1b83ac5c485e542";
        hash = "sha256-JeXjNds4Gc+dkieA0TQmbhoPvozAx/23FO8HgjQu5wE=";
        unpack = true;
      };
    }
    {
      name = "N-V-__8AANUVVwDVcoOf9vCuxr9NUBhMvdV-XuREQFIxja8H";
      path = fetchZigArtifact {
        name = "lsqpack";
        url = "git+https://github.com/litespeedtech/ls-qpack#91567706c41c0d97ab8dc576873ecd472d7869fa";
        hash = "sha256-kbwtvlEmWBA+qUUwYhpZuh5rvNxBum30d6RQDbAF5AM=";
        unpack = true;
      };
    }
    {
      name = "N-V-__8AABlSZwC2bZHS0kM4Fi6Cz3MPxNN3TFeim4QI6R9A";
      path = fetchZigArtifact {
        name = "lsquic";
        url = "git+https://github.com/litespeedtech/lsquic#d5929af7cec6fd74f1cfea2cb1c07c27ce9102b1";
        hash = "sha256-kb47Ibl3S9sBsNuhyaYhh1ix9Jb60FOMkCGVD6FIizU=";
        unpack = true;
      };
    }
    {
      name = "napi_zig-0.2.0-XRkY0XcYAgDV-EwyPZo287cfJkKZaES9crzUCRoqcQ09";
      path = fetchZigArtifact {
        name = "napi_zig";
        url = "git+https://github.com/yuku-toolchain/napi-zig?ref=v0.3.1#1032d3e9da30bd0e8ab895886cb862d45fb56230";
        hash = "sha256-4P9gn24mcGLlWw5vl8Vfi0HrgJr9H5iIpkfRkv3bf/c=";
        unpack = true;
      };
    }
    {
      name = "uWebZockets-1.8.0-SD3SPCtoJgB2t5E5ldRsnhw2iSXJXaEU03GScHvbL_8s";
      path = fetchZigArtifact {
        name = "uWebZockets";
        url = "git+https://github.com/farbenbuilds/uWebZockets?ref=v1.8.0#d94b4e546000455f2ca680d07cb61d032034d5ec";
        hash = "sha256-npIlMFsknfluxXW81uX9DUJnD600NiwLMQpn92rB1/4=";
        unpack = true;
      };
    }
    {
      name = "N-V-__8AAJ2cNgAgfBtAw33Bxfu1IWISDeKKSr3DAqoAysIJ";
      path = fetchZigArtifact {
        name = "zlib";
        url = "https://github.com/madler/zlib/releases/download/v1.3.2/zlib-1.3.2.tar.gz";
        hash = "sha256-uzKaCizQJ00FUZ1hxmfAYuBpkNcuEl7i36jeZPARnRY=";
        unpack = false;
      };
    }
    {
      name = "zslay-0.2.1-OB-IfBl0AQCHCIVUH0AbAjErcCG_LNkaLp8Gz1BUXnoy";
      path = fetchZigArtifact {
        name = "zslay";
        url = "https://github.com/farbenbuilds/zslay/archive/refs/tags/v0.2.1.tar.gz";
        hash = "sha256-ogoYdgzWM0nD/Q8rUE37UzH1tXCPEWHs7Fm60nqbU54=";
        unpack = true;
      };
    }
  ]
  [
  ]
